{% set name = "pyocd" %}
{% set version = "0.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyocd-{{ version }}.tar.gz
  sha256: 1696b6204b0b390f3294623fe43ea1fb6da3d69bebbc4f48308ca10adc8ceaa5

build:
  noarch: python
  entry_points:
    - pyocd = pyocd.__main__:main
    - pyocd-gdbserver = pyocd.tools.gdb_server:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - capstone >=4.0,<5.0
    - cmsis-pack-manager >=0.4.0,<1.0
    - colorama <1.0
    - dataclasses
    - hidapi >=0.10.1,<1.0
    - intelhex >=2.0,<3.0
    - intervaltree >=3.0.2,<4.0
    - libusb-package >=1.0,<2.0
    - natsort >=8.0.0,<9.0
    - prettytable >=2.0,<4.0
    - pyelftools <1.0
    - pylink-square >=0.11.1,<1.0
    - python >=3.6
    - pyusb >=1.2.1,<2.0
    - pyyaml >=6.0,<7.0
    - six >=1.15.0,<2.0
    - typing-extensions >=4.0,<5.0

test:
  commands:
    - pip check
    - pyocd --help
    - pyocd-gdbserver --help
  requires:
    - pip

about:
  home: https://github.com/pyocd/pyOCD
  summary: Cortex-M debugger for Python
  dev_url: https://github.com/pyocd/pyOCD
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rudispr
